import { useEffect,useMemo,useRef,useState } from 'react';
import cytoscape,{type Core,type ElementDefinition} from 'cytoscape';
import {Maximize2,Play,RotateCcw,X} from 'lucide-react';
import type {AwarenessBeat} from '../../types/sapiensTypes';
type R=Record<string,unknown>; type N={id:string;label:string;kind:string;lane:number;source:string;status:string;order:number;data:R;winner?:boolean;muted?:boolean}; type E={source:string;target:string;type:string};
const rec=(v:unknown):R=>v&&typeof v==='object'&&!Array.isArray(v)?v as R:{}; const str=(v:unknown)=>typeof v==='string'?v:''; const list=(v:unknown)=>Array.isArray(v)?v:[]; const banned=/(credential|secret|token|password|argument|\bargs?\b|payload|result|prompt)/i;
const safe=(v:unknown):unknown=>Array.isArray(v)?v.map(safe):v&&typeof v==='object'?Object.fromEntries(Object.entries(v as R).filter(([k])=>!banned.test(k)).map(([k,x])=>[k,safe(x)])):v;
const title=(x:R,f:string)=>str(x.content)||str(x.title)||str(x.summary)||str(x.handle)||f;
function build(beat:AwarenessBeat){const ns:N[]=[],es:E[]=[];const add=(n:N)=>(ns.push(n),n.id);const fresh=beat.candidate_summary?.candidates??beat.candidate_summary?.bounded_candidates??[],held=beat.candidate_summary?.held_candidates??[],winner=rec(beat.winner),wh=str(winner.handle);const sourceIds=new Map<string,string>();
 const source=(name:string)=>{name=name||'unknown source';if(sourceIds.has(name))return sourceIds.get(name)!;const id=`source-${sourceIds.size}`;sourceIds.set(name,id);add({id,label:name,kind:'source / engine',lane:0,source:name,status:'offered',order:1,data:{source:name}});return id};
 add({id:'trigger',label:beat.mode==='autonomous'?'Autonomous tick':beat.trigger_source||'Incoming event',kind:'trigger',lane:0,source:beat.trigger_source||beat.mode,status:'observed',order:0,data:{mode:beat.mode,trigger_source:beat.trigger_source,started_at:beat.started_at,correlation_id:beat.correlation_id}});
 fresh.forEach((v,i)=>{const x=rec(v),s=str(x.source)||'unknown source',id=add({id:`new-${i}`,label:title(x,'New input'),kind:'newly collected input',lane:0,source:s,status:str(x.status)||'collected',order:2,data:x,winner:str(x.handle)===wh,muted:Boolean(wh&&str(x.handle)!==wh)});es.push({source:source(s),target:id,type:'identity'})});
 held.forEach((v,i)=>{const x=rec(v),h=str(x.handle),a=(beat.attention??[]).find(q=>q.handle===h&&q.source===str(x.source)),id=add({id:`held-${i}`,label:title(x,'Competing candidate'),kind:str(x.status)==='carried'?'carried candidate':'attention candidate',lane:1,source:str(x.source)||'unknown',status:str(x.status)||'held',order:3,data:{...x,attention:a},winner:h===wh,muted:Boolean(wh&&h!==wh)});fresh.forEach((q,j)=>{if(h&&str(rec(q).handle)===h)es.push({source:`new-${j}`,target:id,type:'identity'})})});
 const ff=rec(beat.focus_formation);let focus='';if(Object.keys(ff).length||Object.keys(winner).length){focus=add({id:'focus',label:title(ff,title(winner,'Formed focus')),kind:'formed working focus',lane:2,source:'awareness',status:'selected',order:4,data:{winner,...ff,preparation:beat.preparation},winner:true});const cs=list(ff.contributors).map(rec);held.forEach((v,i)=>{const h=str(rec(v).handle);if(h&&(h===wh||cs.some(c=>str(c.handle)===h)))es.push({source:`held-${i}`,target:focus,type:'selected'})})}
 const ctx=list(rec(beat.curation).selected_context).map(rec);ctx.forEach((x,i)=>{const s=str(x.source)||'unknown source',id=add({id:`ctx-${i}`,label:title(x,'Curated context'),kind:`context · ${str(x.resolution_role)||'role unavailable'}`,lane:3,source:s,status:'selected',order:5,data:x,winner:Boolean(x.focus_contributor)});es.push({source:source(s),target:id,type:'identity'})});
 const all=[...(beat.events??[])].sort((a,b)=>(a.sequence??9999)-(b.sequence??9999)),assessmentEvent=all.find(e=>e.stage==='outcome_assessment'),commit=all.find(e=>e.stage==='thought_commit'),events=all.filter(e=>!['outcome_assessment','thought_commit'].includes(e.stage||''));let prior='',first='',terminal='';events.forEach((e,i)=>{const d={...rec(e),...rec(e.detail)},controller=e.stage==='controller'||Boolean(d.move),id=add({id:`ev-${i}`,label:e.title||e.summary||e.stage||'Event',kind:controller?`controller · ${str(d.move)||e.status||'observed'}`:`${e.actor||e.stage||'event'}`,lane:controller?4:5,source:e.actor||e.stage||'unknown',status:e.status||str(d.status)||str(d.move)||'observed',order:10+(e.sequence??i),data:d});if(controller){first||=id;terminal=id}if(prior)es.push({source:prior,target:id,type:e.reference_id?'causal':'sequence'});prior=id});if(first){if(focus)es.push({source:focus,target:first,type:'selected'});ctx.forEach((_,i)=>es.push({source:`ctx-${i}`,target:first,type:'selected'}))}
 const assessment=rec(beat.assessment);let aid='';if(Object.keys(assessment).length){aid=add({id:'assessment',label:str(assessment.understanding)||str(assessment.reason)||'Outcome assessment',kind:'authoritative assessment',lane:6,source:'awareness',status:str(assessment.state)||'assessed',order:100,data:{...rec(assessmentEvent?.detail),...assessment}});if(terminal||prior)es.push({source:terminal||prior,target:aid,type:'sequence'})}if(commit){const d={...rec(commit),...rec(commit.detail)};const id=add({id:'commit',label:str(assessment.understanding)||commit.summary||'Thought committed',kind:'retained understanding commit',lane:7,source:commit.actor||'awareness',status:commit.status||'committed',order:110,data:d});if(aid)es.push({source:aid,target:id,type:'causal'})}
 const td=rec(all.filter(e=>e.stage==='controller').at(-1)?.detail);let response='';if(str(td.move)==='speak'&&str(td.response)){response=add({id:'response',label:str(td.response),kind:'generated response',lane:7,source:'awareness',status:'generated',order:111,data:{response:td.response}});if(terminal)es.push({source:terminal,target:response,type:'causal'})}const delivery=rec(beat.delivery);if(Object.keys(delivery).length){const id=add({id:'delivery',label:str(delivery.route)||'Delivery route',kind:'delivery destination',lane:7,source:'delivery',status:str(delivery.status)||'recorded',order:120,data:delivery});if(response&&delivery.response_present)es.push({source:response,target:id,type:'causal'});else if(aid)es.push({source:aid,target:id,type:'sequence'})}return{ns,es,legacy:!held.length&&!ctx.length&&!beat.assessment}}
export function AwarenessFlowGraph({beat}:{beat:AwarenessBeat}){const model=useMemo(()=>build(beat),[beat]),host=useRef<HTMLDivElement>(null),graph=useRef<Core|null>(null),[selected,setSelected]=useState<N|null>(null),[step,setStep]=useState(9999),[source,setSource]=useState('all'),[status,setStatus]=useState('all');const sources=[...new Set(model.ns.map(n=>n.source))],statuses=[...new Set(model.ns.map(n=>n.status))];
 useEffect(()=>{if(!host.current||model.legacy)return;const rows=new Map<number,number>(),els:ElementDefinition[]=[...model.ns.map(n=>{const row=rows.get(n.lane)??0;rows.set(n.lane,row+1);return{data:{id:n.id,label:n.label,raw:n,order:n.order,source:n.source,status:n.status},position:{x:100+n.lane*215,y:60+row*82},classes:`${n.winner?'winner ':''}${n.muted?'muted':''}`}}),...model.es.map((e,i)=>({data:{id:`e${i}`,source:e.source,target:e.target},classes:e.type}))];const c=cytoscape({container:host.current,elements:els,layout:{name:'preset'},minZoom:.2,maxZoom:2,style:[{selector:'node',style:{label:'data(label)',width:145,height:54,shape:'round-rectangle','background-color':'#172033','border-color':'#64748b','border-width':1,color:'#dbeafe','font-size':9,'text-wrap':'ellipsis','text-max-width':125,'text-valign':'center','text-halign':'center'}},{selector:'node.winner',style:{'border-color':'#34d399','border-width':3}},{selector:'node.muted',style:{opacity:.35}},{selector:'edge',style:{'target-arrow-shape':'triangle','curve-style':'bezier','line-color':'#64748b','target-arrow-color':'#64748b'}},{selector:'edge.identity',style:{'line-color':'#38bdf8','target-arrow-color':'#38bdf8'}},{selector:'edge.selected',style:{width:3,'line-color':'#34d399','target-arrow-color':'#34d399'}},{selector:'edge.sequence',style:{'line-style':'dashed'}},{selector:'edge.causal',style:{width:2.5,'line-color':'#c084fc','target-arrow-color':'#c084fc'}}]});c.on('tap','node',e=>setSelected(e.target.data('raw')));graph.current=c;c.fit(undefined,20);return()=>c.destroy()},[model]);
 useEffect(()=>{const c=graph.current;if(!c)return;c.nodes().forEach(n=>n.style('display',n.data('order')<=step&&(source==='all'||n.data('source')===source)&&(status==='all'||n.data('status')===status)?'element':'none'));c.edges().forEach(e=>e.style('display',e.source().visible()&&e.target().visible()?'element':'none'))},[step,source,status]);if(model.legacy)return <div className="rounded-xl border border-amber-400/15 p-4 text-xs text-amber-100/60">Legacy beat: use the chronological event log; missing graph links are not inferred.</div>;
 return <section className="relative overflow-hidden rounded-xl border border-white/[.07] bg-[#080d18]"><header className="flex flex-wrap gap-2 border-b border-white/[.06] p-3"><span className="mr-auto text-xs text-white/60">Inputs · Attention · Focus · Context · Decision loop · Assessment · Outputs</span><select value={source} onChange={e=>setSource(e.target.value)} className="bg-[#101827] text-xs"><option value="all">All sources</option>{sources.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="bg-[#101827] text-xs"><option value="all">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setStep(s=>s===9999?0:s+1)}>{step===9999?<RotateCcw/>:<Play/>}</button><button onClick={()=>{setStep(9999);graph.current?.fit(undefined,20)}}><Maximize2/></button></header><div className="px-3 py-2 text-[9px] text-white/35">Blue exact identity · Green selected/informed · Dashed sequence only · Violet causal/result</div><div ref={host} className="hidden h-[480px] md:block"/><ol className="p-3 md:hidden">{model.ns.filter(n=>n.order<=step).map(n=><li key={n.id}><button onClick={()=>setSelected(n)} className="mb-2 w-full rounded border border-white/10 p-3 text-left text-xs">{n.kind}: {n.label}</button></li>)}</ol>{selected&&<aside className="absolute inset-y-0 right-0 z-10 w-full max-w-sm overflow-auto border-l border-white/10 bg-[#09101c] p-4"><button onClick={()=>setSelected(null)} className="float-right"><X/></button><p className="text-xs text-cyan-200/50">{selected.kind}</p><h4 className="mt-2 text-sm">{selected.label}</h4><p className="mt-3 text-xs text-white/40">Source: {selected.source} · Status: {selected.status}</p>{str(selected.data.content)&&<p className="mt-4 whitespace-pre-wrap text-xs text-white/65">{str(selected.data.content)}</p>}<details className="mt-4"><summary className="cursor-pointer text-xs text-white/40">Safe technical fields</summary><pre className="mt-2 whitespace-pre-wrap text-[9px] text-white/40">{JSON.stringify(safe(selected.data),null,2)}</pre></details></aside>}</section>}
