export type SimulationStatus = 'created' | 'starting' | 'scheduled' | 'paused' | 'running' | 'stopping' | 'completed' | 'blocked' | 'stopped' | 'limit_reached' | 'failed' | 'recovery_required';
export interface CaseInfo { case_id: string; version: string; title: string; description: string; suggested_start_at: string; start_constraint: string; participant_mode: string; sapien_integration_available: boolean; interpreter_mode: string; limitations: string }
export interface CaseCatalog { cases: CaseInfo[]; defaults: { speed: number; max_wall_seconds: number; max_records: number }; limits: { max_speed: number; max_wall_seconds: number; max_records: number; max_runs: number; max_active: number; retention_seconds: number }; worker_id: number; storage: string; single_worker_required: boolean; automatic_recovery_available: boolean }
export interface ParticipantState { phase: string; cycles: number; incoming_turns: number; last_tick_at: string | null; last_cycle_wall_seconds: number | null; last_cycle_simulated_seconds: number | null; pending_messages: number; failure_type: string | null }
export interface SimulationRun { run_id: string; status: SimulationStatus; archived?: boolean; runtime_available?: boolean; case_id: string; case_version: string; participant_id: string | null; sapien_id: number | null; start_blocked_reason: string | null; participant_mode: 'sapien' | 'manual' | 'environment_only'; interpreter_mode: string; sapien_integration_available: boolean; start_at: string; end_at: string; simulated_time: string; scheduled_start_at: string | null; execution_started_at: string | null; delete_requested: boolean; cleanup_required: boolean; speed: number; paused: boolean; config: { run_id: string; speed: number; max_wall_seconds: number; max_records: number }; participant: ParticipantState | null; wall_elapsed_seconds: number; wall_remaining_seconds: number; expires_in_seconds: number | null; event_count: number; diagnostic_counts: Record<string, number>; pending_world_work: number | null; detail: string | null; allowed_controls: string[]; participant_actions_available: boolean }
export interface SimulationEvent { record_id: string; run_id: string; sequence: number; source: string; occurred_at: string; observed_at: string; scheduled_at: string | null; operation_id: string | null; payload: Record<string, unknown> }
export interface EventPage { events: SimulationEvent[]; next_after: number; has_more: boolean }
export interface SimulationMetric { expectation_id: string; verdict: 'pass' | 'fail' | 'insufficient_evidence'; explanation: string; evidence_ids: string[] }
export interface SimulationResult { run_id: string; status: SimulationStatus; detail: string; report: { metrics: SimulationMetric[]; diagnostics: SimulationEvent[] }; pass_rate: number | null }
export interface SimulationList { worker_id: number; history_limit: number; runs: SimulationRun[] }
export interface CaseCreateRequest { case: { case_id: string; version: string; start_at: string; participant_id: string; participant_name: string }; config: { run_id: string; speed?: number; max_wall_seconds?: number; max_records?: number }; sapien_id: number }
export interface ParticipantOutcome { participant_id: string; operation_id: string; outcome: { success?: boolean; is_error?: boolean; content?: string; reason?: string; [key: string]: unknown } }
export interface DebugGuide { run_id: string; visibility: 'admin_only'; people: { person_id: string; name: string }[]; channels: unknown[]; connections: string[]; expectations: unknown[]; rules: unknown[]; employee_commands: { person_id: string; options: { command: string; description: string }[] }[] }

export interface WorldBase { run_id: string; visibility: 'admin_only'; archived: boolean; through: number; state_basis: 'recorded_evidence'; directory_available: boolean; participant_id: string | null }
export interface WorldOverview extends WorldBase { counts: { employees: number; channels: number; connections: number; tickets: number } }
export interface WorldEmployee { person_id: string; name: string; sent: number; received: number; tool_calls: number; last_activity_at: string | null }
export interface WorldChannel { channel_id: string; title: string; members: string[]; posts: number }
export interface WorldConnection { connection: string; tool_calls: number; errors: number }
export interface WorldTicket { connection: string; issue_key: string; summary: string | null; description: string | null; status: string | null; last_recorded_at: string | null; evidence_id: string | null; has_snapshot: boolean }
export interface WorldCollection<T> extends WorldBase { items: T[]; total: number; next_offset: number; has_more: boolean }
export type WorldActivityCategory = 'messages' | 'tools' | 'changes' | 'rejections';
export interface WorldActivityItem { category: WorldActivityCategory; actor_id: string | null; connection: string; issue_key: string | null; event: SimulationEvent; recipient_ids?: string[]; delivery_evidence_ids?: string[] }
export interface WorldActivityPage extends WorldBase { items: WorldActivityItem[]; next_after: number; has_more: boolean }
export interface WorldQuery { through?: number; offset?: number; after?: number; limit?: number; person_id?: string; channel_id?: string; connection?: string; issue_key?: string; kind?: WorldActivityCategory; direction?: 'sent' | 'received'; search?: string; status?: string }

export interface InspectionQuery { through?: number; after?: number; offset?: number; limit?: number; category?: InspectionCategory; person_id?: string; channel_id?: string; connection?: string; issue_key?: string; since?: string; until?: string; week?: number }
export type InspectionCategory = 'message' | 'tool' | 'reaction' | 'scenario' | 'rejection' | 'issue' | 'availability' | 'knowledge' | 'lifecycle';
export interface InspectionBase { schema_version: 1; run_id: string; visibility: 'admin_only'; archived: boolean; through: number; latest_at_capture: number; generated_at: string; observed_at?: string | null; simulated_evidence_at?: string | null; state_basis: string; snapshot_scope: 'evidence_prefix'; partial: boolean; specification_available: boolean; participant_id: string | null }
export interface InspectionActivity { record_id: string; sequence: number; category: InspectionCategory; event_type: string; occurred_at: string; observed_at: string; connection: string | null; person_ids: string[]; channel_id: string | null; issue_key: string | null; rule_id: string | null; event_id: string | null; message_id: string | null; reply_to_message_id: string | null; operation_id: string | null; related_record_ids: string[]; expectation_ids: string[]; simulation_week: number | null; state_basis: string; payload: Record<string, unknown>; arguments: Record<string, unknown> | null; result: Record<string, unknown> | null }
export interface InspectionCasePhase { phase_id: string; title: string; start_at: string; end_at: string }
export interface InspectionCaseWorkItem { issue_key: string; title: string; owner_id: string; target_week: number; dependencies: string[] }
export interface InspectionPersonSeed { person_id: string; name: string; facts: Array<{ key: string; text: string }>; available_at?: string | null }
export interface InspectionChannelSeed { channel_id: string; title: string; members: string[] }
export interface InspectionCaseSpecification { schema_version: 1; overview: { mission: string; phases: InspectionCasePhase[]; limitations: string[]; backlog: InspectionCaseWorkItem[] } | null; scenario: { scenario_id: string; version: string; start_at: string; end_at: string; initial_world: { people: InspectionPersonSeed[]; channels: InspectionChannelSeed[] }; events: Array<Record<string, unknown>>; program: { rules: Array<Record<string, unknown>>; employees: Array<Record<string, unknown>>; hours: Array<Record<string, unknown>> } | null }; expectations: Array<Record<string, unknown>>; connection_seeds: Array<{ name: string; seed: unknown }> }
export interface InspectionSpecificationResponse extends InspectionBase { specification: InspectionCaseSpecification | null; legacy_guide: DebugGuide | null }
export interface InspectionObjective { expectation_id: string; title: string; expected_behavior: Record<string, unknown>; observed_behavior: Record<string, unknown> | null; verdict: 'pass' | 'fail' | 'insufficient_evidence' | 'not_evaluated'; evidence_ids: string[]; missing_actions: unknown; state_basis: string }
export interface InspectionOverview extends InspectionBase { run_status: string; current_phase: InspectionCasePhase | null; phase_basis: string; counts: Record<InspectionCategory, number>; message_summary: { unique_messages: number; deliveries: number }; tool_summary: { calls?: number; errors?: number }; recorded_blockers: InspectionProgressItem[]; unresolved_decisions: unknown; recent_activity: InspectionActivity[]; objectives: InspectionObjective[] }
export interface InspectionActivityPage extends InspectionBase { items: InspectionActivity[]; has_more: boolean; next_after: number; understanding_verified: false }
export interface InspectionPerson extends InspectionPersonSeed { sent: number; received: number; tool_calls: number; last_activity_at: string | null; available_at: string | null; role: string | null; authored_context: string | null; project_context: string | null; organization: string | null; responsibilities: unknown; authority_boundaries: unknown; relationships: unknown; state_basis: string; working_hours: Record<string, unknown> | null; owned_issues: string[] }
export interface InspectionProgressItem { rule?: Record<string, unknown>; event?: Record<string, unknown>; status: 'fired' | 'waiting' | 'blocked' | 'review_needed' | 'released' | 'unavailable'; state_basis?: string; last_decision?: InspectionActivity | null; condition_status?: 'unavailable'; evidence?: InspectionActivity | null }
export interface InspectionCollection<T> extends InspectionBase { items: T[]; total: number; next_offset: number; has_more: boolean }
export interface InspectionResults extends InspectionCollection<InspectionObjective> { evaluation_available: boolean }
